---
- name: Install prerequisites
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
    update_cache: yes

- name: Create directory for apt keyrings
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download and import Kubernetes GPG key
  uri:
    url: https://pkgs.k8s.io/core:/stable:/v1.34/deb/Release.key
    return_content: yes
  register: k8s_key

- name: Save GPG key to keyring
  shell: |
    echo "{{ k8s_key.content }}" | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  args:
    creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg

- name: Set correct permissions for the keyring
  file:
    path: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
    mode: '0644'

- name: Add Kubernetes repository
  apt_repository:
    repo: 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.34/deb/ /'
    state: present
    filename: kubernetes
    update_cache: yes

- name: Install kubelet, kubeadm and kubectl
  apt:
    name: ['kubelet=1.34.0-1.1', 'kubeadm=1.34.0-1.1', 'kubectl=1.34.0-1.1']
    update_cache: yes

- name: Hold kubelet, kubeadm and kubectl
  dpkg_selections:
    name: '{{ item }}'
    selection: hold
  with_items:
    - kubelet
    - kubeadm
    - kubectl
