---
name: build
on: [push, workflow_dispatch]
jobs:
  integration_test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Python 3.13
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"
          cache: "pip"

      - name: Install Python 3 requirements
        run: pip install -r requirements.txt

      - name: Install VirtualBox
        run: |
          sudo apt-get update
          sudo apt-get install -y virtualbox

      - name: Install Vagrant
        run: |
          wget -O - https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(grep -oP '(?<=UBUNTU_CODENAME=).*' /etc/os-release || lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt update && sudo apt install vagrant

      - name: Enable KVM support
        run: |
          sudo apt-get install -y qemu-kvm libvirt-daemon-system libvirt-clients bridge-utils
          sudo modprobe -v kvm 
          #sudo modprobe kvm_intel

      - name: Verify virtualisation
        run: |
          lscpu
          sudo kvm-ok || true

      - name: Spawn Vagrant VMs
        run: VAGRANT_DISABLE_VBOXSYMLINKCREATE=1 vagrant up

      - name: Make cluster
        run: make cluster

      - name: Wait for node kubemaster to be ready
        run: vagrant ssh -c 'kubectl wait --for=condition=Ready node/kubemaster --timeout=120s' kubemaster

      - name: Wait for node worker1 to be ready
        run: vagrant ssh -c 'kubectl wait --for=condition=Ready node/worker1 --timeout=120s' kubemaster

      - name: Wait for node worker2 to be ready
        run: vagrant ssh -c 'kubectl wait --for=condition=Ready node/worker2 --timeout=120s' kubemaster

      - name: Get nodes
        run: vagrant ssh -c 'kubectl get nodes' kubemaster

      - name: Wait for all pods to be ready
        run: vagrant ssh -c 'kubectl wait --for=condition=Ready pod --all --all-namespaces --timeout=180s' kubemaster
