---
name: build
on: [push, workflow_dispatch]
jobs:
  integration_test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Create Python 3 virtualenv
        uses: syphar/restore-virtualenv@v1
      - name: Install Python 3 requirements
        run: pip install -r requirements.txt
      - name: Update apt
        run: sudo apt update
      - name: Install VirtualBox
        run: sudo  apt install -y virtualbox
      # There seems to be not Github Action for setting up Vagrant, so D.I.Y.
      - name: Download Vagrant
        run: curl https://releases.hashicorp.com/vagrant/2.2.9/vagrant_2.2.9_x86_64.deb -o /tmp/vagrant.deb
      - name: Install Vagrant
        run: sudo dpkg -i /tmp/vagrant.deb
      - name: Create custom Vagrantfile to disable VT-x
        run: |
          mkdir -v ~/.vagrant.d
          tee ~/.vagrant.d/Vagrantfile << EOF
          Vagrant.configure("2") do |config|
            config.vm.provider :virtualbox do |vb|
              vb.customize ["modifyvm", :id, "--hwvirtex", "off"]
            end
          end
          EOF
      - name: Spawn Vagrant VMs
        run: vagrant up
      - name: Make cluster
        run: make cluster
      - name: Get nodes
        run: vagrant ssh -c kubectl get nodes
